openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
- url: /
paths:
  /example:
    get:
      responses:
        "200":
          description: Success
      summary: Get example
      x-accepts: application/json
components:
  schemas: {}

